services:
  legacy_mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: legacy_mysql
    env_file: ./.env
    environment:
      - MYSQL_USER=$LEGACY_MYSQL_USER
      - MYSQL_PASSWORD=$LEGACY_MYSQL_PASSWORD
      - MYSQL_DATABASE=$LEGACY_MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$LEGACY_MYSQL_PASSWORD
    ports:
      - $LEGACY_MYSQL_PORT:3306
    expose:
      - $LEGACY_MYSQL_PORT

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
    container_name: mysql
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    expose:
      - $MYSQL_PORT

  legacy_mysql_read_replica:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: legacy_mysql_read_replica
    env_file: ./.env
    environment:
      - MYSQL_USER=$LEGACY_MYSQL_READ_REPLICA_USER
      - MYSQL_PASSWORD=$LEGACY_MYSQL_READ_REPLICA_PASSWORD
      - MYSQL_DATABASE=$LEGACY_MYSQL_READ_REPLICA_DATABASE
      - MYSQL_ROOT_PASSWORD=$LEGACY_MYSQL_READ_REPLICA_PASSWORD
    ports:
      - $LEGACY_MYSQL_READ_REPLICA_PORT:3306
    expose:
      - $LEGACY_MYSQL_READ_REPLICA_PORT

  pg:
    image: postgres:16
    container_name: pg
    env_file: ./.env
    environment:
      - POSTGRES_DB=$PG_DATABASE
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
    ports:
      - $PG_PORT:5432
    expose:
      - $PG_PORT

  pg_read_replica:
    image: postgres:16
    container_name: pg_read_replica
    env_file: ./.env
    environment:
      - POSTGRES_DB=$PG_READ_REPLICA_DATABASE
      - POSTGRES_USER=$PG_READ_REPLICA_USER
      - POSTGRES_PASSWORD=$PG_READ_REPLICA_PASSWORD
    ports:
      - $PG_READ_REPLICA_PORT:5432
    expose:
      - $PG_READ_REPLICA_PORT

  mssql:
    platform: linux/x86_64
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    env_file: ./.env
    environment:
      - SA_PASSWORD=$MSSQL_PASSWORD
      - ACCEPT_EULA='Y'
    ports:
      - $MSSQL_PORT:1433
    expose:
      - $MSSQL_PORT

  mssql_read_replica:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_read_replica
    env_file: ./.env
    environment:
      - SA_PASSWORD=$MSSQL_READ_REPLICA_PASSWORD
      - ACCEPT_EULA='Y'
    ports:
      - $MSSQL_READ_REPLICA_PORT:1433
    expose:
      - $MSSQL_READ_REPLICA_PORT
